
#New items, blocks VanillaTweaks adds.
[Content]
	#Want a food which can be obtained with eggs and heals 2.5 hunger?
	enableFriedEgg = false
	#Want to showcase your treasure but item frame doesn't satisfy you?
	enablePedestal = false
	#Want block forms of flint, charcoal and sugar?
	enableStorageBlocks = false
	#Do you want a portable crafting table?
	enablePad = false
	#How much do you want the binoculars to zoom? ( 0 = disabled)
	#Range: 0.0 ~ 1.7976931348623157E308
	binocularZoomAmount = 0
	#Want to identity slime chunks in-game?
	enableSlimeBucket = false
	#Want a less effective but throwable TNT?
	enableDynamite = false

