
#Modification of vanilla_recipes recipes and addition of new recipes regarding vanilla_recipes
[Crafting]
	#Have wool but need string?
	string = false
	#Cobblestone used in stone tools doesn't make sense?
	betterStoneTools = false
	#Tired of not having a nametag?
	nametag = false
	#Wanna craft multiple chests at one go?
	betterChest = false
	#Want 8 stairs rather than 4 in stairs recipe?
	betterStairs = false

