
#Mob Settings
[mobs]
	#Small Spider Biomes
	smallSpiderBiomes = []
	#Maw Biomes
	mawBiomes = []
	#Firefly Biomes
	fireflyBiomes = []
	#Shade Biomes
	shadeBiomes = []
	#Haunt Biomes
	hauntBiomes = []
	#Specter Biomes
	specterBiomes = []
	#Phantasm Biomes
	phantasmBiomes = []
	#Friendly Maw Foods
	mawFoods = []
	#Watcher Biomes
	watcherBiomes = []
	#Snail Biomes
	snailBiomes = []
	#Grizzly Bear Biomes
	grizzlyBearBiomes = ["minecraft:taiga", "minecraft:taiga_hills", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "projectvibrantjourneys:boreal_forest", "projectvibrantjourneys:snowy_boreal_forest", "projectvibrantjourneys:boreal_plateau", "projectvibrantjourneys:redwoods", "projectvibrantjourneys:redwood_peaks"]
	#Add skeletal knights to dungeons
	skeletalKnightDungeons = true
	#Ice Cube Biomes
	icecubeBiomes = ["minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:snowy_mountains", "minecraft:snowy_tundra", "minecraft:ice_spikes", "minecraft:frozen_river", "minecraft:snowy_beach"]
	#Clam Biomes
	clamBiomes = []
	#Skeletal Knight Biomes
	skeletalKnightBiomes = ["minecraft:ocean", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:frozen_ocean", "minecraft:deep_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:forest", "minecraft:wooded_hills", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:mountains", "minecraft:snowy_mountains", "minecraft:mountain_edge", "minecraft:wooded_mountains", "minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "minecraft:desert", "minecraft:desert_hills", "minecraft:desert_lakes", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:badlands", "minecraft:wooded_badlands_plateau", "minecraft:badlands_plateau", "minecraft:eroded_badlands", "minecraft:modified_wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:snowy_tundra", "minecraft:ice_spikes", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "minecraft:river", "minecraft:frozen_river", "minecraft:beach", "minecraft:stone_shore", "minecraft:snowy_beach", "projectvibrantjourneys:overgrown_spires", "projectvibrantjourneys:verdant_sands", "projectvibrantjourneys:boreal_forest", "projectvibrantjourneys:snowy_boreal_forest", "projectvibrantjourneys:boreal_plateau", "projectvibrantjourneys:willow_wetlands", "projectvibrantjourneys:redwoods", "projectvibrantjourneys:redwood_peaks", "projectvibrantjourneys:baobab_fields", "projectvibrantjourneys:aspen_grove", "projectvibrantjourneys:crimson_thicket", "projectvibrantjourneys:prairie"]
	#Tropical Fish Biomes
	tropicalFishBiomes = []
	#Fly Biomes
	flyBiomes = []
	#Wraith Biomes
	wraithBiomes = []
	#Banshee Biomes
	bansheeBiomes = []
	#Ghost Biomes
	ghostBiomes = []
	#Starfish Biomes
	starfishBiomes = []
	#Slug Biomes
	slugBiomes = []
	#Mute Flies
	muteFlies = false
	#Nightmare Biomes
	nightmareBiomes = []

#Biome Settings
[biomes]
	#Baobab Fields Weight
	#Range: 0 ~ 100
	baobabFieldsWeight = 2
	#Boreal Plateau Weight
	#Range: 0 ~ 100
	borealPlateauWeight = 0
	#Boreal Forest Weight
	#Range: 0 ~ 100
	borealForestWeight = 0
	#Redwoods Weight
	#Range: 0 ~ 100
	redwoodsWeight = 0
	#Crimson Thicket Weight
	#Range: 0 ~ 100
	crimsonThicketWeight = 0
	#Overgrown Spires Weight
	#Range: 0 ~ 100
	overgrownSpiresWeight = 1
	#Willow Wetlands Weight
	#Range: 0 ~ 100
	willowWetlandsWeight = 0
	#Prairie Weight
	#Range: 0 ~ 100
	prairieWeight = 0
	#Snowy Boreal Forest Weight
	#Range: 0 ~ 100
	snowyBorealForestWeight = 0
	#Aspen Grove Weight
	#Range: 0 ~ 100
	aspenGroveWeight = 0
	#Verdant Sands Weight
	#Range: 0 ~ 100
	verdantSandsWeight = 5
	#Redwood Peaks Weight
	#Range: 0 ~ 100
	redwoodPeaksWeight = 0

#World Gen Settings
[worldgen]
	#Normal frequency
	oakTreesBiomes = []
	#Sparse frequency
	darkOakTreesSparseBiomes = []
	#Sandstone Rocks Biomes
	sandstoneRocksBiomes = []
	#Seagrass Biomes
	seagrassBiomes = []
	#Sparse frequency
	pineTreesSparseBiomes = []
	#Sparse frequency
	firTreesSparseBiomes = []
	#Dung Biomes
	dungBiomes = []
	#Seashells Biomes
	seashellsBiomes = []
	#Gold Nugget Biomes (Common)
	goldNuggetCommonBiomes = []
	#Sparse frequency
	jungleTreesSparseBiomes = []
	#Sparse frequency
	baobabTreesSparseBiomes = []
	#Normal frequency
	purpleMapleTreesBiomes = []
	#Normal frequency
	acaciaTreesBiomes = []
	#Netherrack Rocks Biomes
	netherrackRocksBiomes = []
	#Normal frequency
	juniperTreesBiomes = []
	#Sparse frequency
	mangroveTreesSparseBiomes = []
	#Lily Pad Biomes
	lilypadBiomes = ["minecraft:plains", "minecraft:sunflower_plains", "minecraft:forest", "minecraft:wooded_hills", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:mountains", "minecraft:mountain_edge", "minecraft:wooded_mountains", "minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "minecraft:river", "projectvibrantjourneys:overgrown_spires", "projectvibrantjourneys:verdant_sands", "projectvibrantjourneys:boreal_forest", "projectvibrantjourneys:snowy_boreal_forest", "projectvibrantjourneys:boreal_plateau", "projectvibrantjourneys:redwood_peaks", "projectvibrantjourneys:aspen_grove", "projectvibrantjourneys:crimson_thicket", "projectvibrantjourneys:prairie"]
	#Frogbit Biomes
	frogbitBiomes = []
	#Normal frequency
	aspenTreesBiomes = []
	#Sparse frequency
	aspenTreesSparseBiomes = []
	#Sparse frequency
	birchTreesSparseBiomes = []
	#Normal frequency
	redMapleTreesBiomes = []
	#Sparse frequency
	acaciaTreesSparseBiomes = []
	#Sparse frequency
	oakTreesSparseBiomes = []
	#Iron Nugget Biomes
	ironNuggetBiomes = []
	#Normal frequency
	jungleTreesBiomes = []
	#Normal frequency
	spruceTreesBiomes = []
	#Normal frequency
	palmTreesBiomes = []
	#Normal frequency
	darkOakTreesBiomes = []
	#Ice Chunks Biomes
	iceChunksBiomes = []
	#Sparse frequency
	willowTreesSparseBiomes = []
	#Flint Biomes
	flintBiomes = []
	#Denser River Grass
	moreGrassInRivers = true
	#Normal frequency
	cottonwoodTreesBiomes = []
	#Sparse frequency
	cottonwoodTreesSparseBiomes = []
	#Beach Grass Biomes
	beachGrassBiomes = []
	#Normal frequency
	willowTreesBiomes = []
	#Bones Nether Biomes
	bonesNetherBiomes = []
	#Bones Biomes
	bonesBiomes = []
	#Duckweed Biomes
	duckweedBiomes = []
	#Bones Biomes (Common)
	bonesCommonBiomes = []
	#Glowcap Biomes
	glowcapBiomes = ["minecraft:nether"]
	#Normal frequency
	pineTreesBiomes = []
	#Normal frequency
	baobabTreesBiomes = []
	#Cobweb Biomes
	cobwebBiomes = []
	#Sparse frequency
	palmTreesSparseBiomes = []
	#Red Sandstone Rocks Biomes
	redSandstoneRocksBiomes = []
	#Normal frequency
	redwoodTreesBiomes = []
	#Sparse frequency
	juniperTreesSparseBiomes = []
	#Pinecones Biomes
	pineconesBiomes = []
	#Gold Nugget Biomes
	goldNuggetBiomes = []
	#Normal frequency
	orangeMapleTreesBiomes = []
	#Sparse frequency
	orangeMapleTreesSparseBiomes = []
	#Sparse frequency
	spruceTreesSparseBiomes = []
	#Small Cactus Biomes
	smallCactusBiomes = ["minecraft:desert", "minecraft:desert_hills", "minecraft:desert_lakes", "projectvibrantjourneys:verdant_sands"]
	#Sparse frequency
	redwoodTreesSparseBiomes = []
	#Short Grass Biomes
	shortGrassBiomes = ["minecraft:ocean", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:frozen_ocean", "minecraft:deep_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:forest", "minecraft:wooded_hills", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest", "minecraft:dark_forest_hills", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:mountains", "minecraft:wooded_mountains", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "minecraft:river", "projectvibrantjourneys:overgrown_spires", "projectvibrantjourneys:verdant_sands", "projectvibrantjourneys:boreal_forest", "projectvibrantjourneys:snowy_boreal_forest", "projectvibrantjourneys:boreal_plateau", "projectvibrantjourneys:willow_wetlands", "projectvibrantjourneys:redwoods", "projectvibrantjourneys:redwood_peaks", "projectvibrantjourneys:baobab_fields", "projectvibrantjourneys:aspen_grove", "projectvibrantjourneys:crimson_thicket", "projectvibrantjourneys:prairie"]
	#Normal frequency
	firTreesBiomes = []
	#Rocks Biomes (Stone, Cobblestone, Andesite, Diorite, Granite)
	rocksBiomes = []
	#Cattail Biomes
	cattailBiomes = []
	#Bark Mushroom Biomes
	barkMushroomBiomes = []
	#Sea Oats Biomes
	seaOatsBiomes = []
	#Sparse frequency
	redMapleTreesSparseBiomes = []
	#Normal frequency
	birchTreesBiomes = []
	#Bush Biomes
	bushBiomes = ["minecraft:plains", "minecraft:sunflower_plains", "projectvibrantjourneys:overgrown_spires", "projectvibrantjourneys:verdant_sands", "projectvibrantjourneys:redwoods", "projectvibrantjourneys:redwood_peaks"]
	#Normal frequency
	mangroveTreesBiomes = []
	#Sparse frequency
	purpleMapleTreesSparseBiomes = []

